-- ═══════════════════════════════════════════════════════════════════════════
-- NAQLA — initial schema
--
-- Principle: the invariants live HERE, not in application code. A rule that a
-- developer can forget to call is not a rule. Every constraint below carries
-- the invariant it enforces in a comment.
--
-- Conventions:
--   - uuid primary keys, generated by the database
--   - created_at / updated_at on every mutable table
--   - explicit owner column (user_id) wherever a row belongs to a person
--   - append-only tables have no UPDATE/DELETE grant (see 0002_rls.sql)
--   - soft deletion only where product requirements need recovery or history
-- ═══════════════════════════════════════════════════════════════════════════

create extension if not exists "pgcrypto";
-- citext: usernames and public slugs are case-insensitive identifiers.
create extension if not exists "citext";

-- ───────────────────────────── enumerations ────────────────────────────────
-- Enums, not text with a CHECK, so an unknown value cannot be inserted at all.

create type evidence_state as enum (
  'gap', 'self_reported', 'practiced', 'demonstrated', 'verified'
);

create type evidence_source_strength as enum (
  'platform_controlled', 'platform_observed', 'third_party_asserted', 'self_reported'
);

create type provenance_class as enum (
  'authoritative', 'curated', 'ai_generated', 'user_generated', 'system_derived'
);

create type evaluation_outcome as enum (
  'passed', 'below_threshold', 'blocked_by_checks', 'undetermined', 'needs_human_review'
);

create type verification_outcome as enum (
  'accepted', 'downgraded', 'rejected', 'escalated_to_human', 'exception_granted'
);

create type ai_usage_mode as enum ('ai_prohibited', 'ai_assisted', 'ai_expected');

create type content_status as enum ('draft', 'in_review', 'published', 'deprecated');

create type visibility as enum ('private', 'shared_by_link', 'public');

create type privacy_class as enum (
  'private_never_shareable', 'private_shareable_derived', 'private_publishable', 'non_personal'
);

create type actor_kind as enum ('user', 'human_reviewer', 'system', 'ai_agent');

create type role_performed as enum ('sme', 'human_reviewer');

-- Ordinal helper. The UI must never derive direction from string order.
create function evidence_ordinal(s evidence_state) returns int
  language sql immutable as $$
    select case s
      when 'gap' then 0 when 'self_reported' then 1 when 'practiced' then 2
      when 'demonstrated' then 3 when 'verified' then 4 end;
  $$;

create function touch_updated_at() returns trigger
  language plpgsql as $$
    begin new.updated_at = now(); return new; end;
  $$;

-- ═══════════════════════════ identity and goal ═════════════════════════════

-- Mirrors auth.users. Supabase owns authentication; the product owns the
-- profile. Kept separate so a change of auth provider does not rewrite
-- product data.
create table app_user (
  id                uuid primary key,             -- equals auth.users.id
  username          citext unique,
  display_name      text not null,
  locale            text not null default 'ar' check (locale in ('ar', 'en')),
  org_id            uuid,                         -- reserved from Phase 1 (D-032)
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  -- Soft deletion: the account is recoverable and the audit trail must survive
  -- a deletion request's grace period (D-024/D-025 retention policy).
  deleted_at        timestamptz
);
create trigger app_user_touch before update on app_user
  for each row execute function touch_updated_at();

comment on column app_user.org_id is
  'Reserved for B2B2C from Phase 1 (D-032). No institutional features exist yet.';

-- Username reuse after deletion is governed by OPEN-017 (cooling period),
-- which is unresolved. Recording the release time now means the policy can be
-- applied later without reconstructing history.
create table username_release (
  username      citext primary key,
  released_at   timestamptz not null default now(),
  released_by   uuid not null
);

create table target_role (
  id                uuid primary key default gen_random_uuid(),
  slug              text not null unique,
  label_ar          text not null,
  label_en          text not null,
  track_id          text not null,
  review_status     content_status not null default 'draft',
  source_label      text not null,
  -- INV-5: a role definition is a fact and carries provenance.
  provenance_class  provenance_class not null,
  provenance_source text not null,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);
create trigger target_role_touch before update on target_role
  for each row execute function touch_updated_at();

comment on table target_role is
  'A role_definition record. The same UI serves any track; nothing is hard-coded to Frontend.';

create table skill (
  id                uuid primary key default gen_random_uuid(),
  slug              text not null unique,
  label_ar          text not null,
  label_en          text not null,
  -- Skills are GLOBAL, not per-track (LBD-08), so cross-track identity holds.
  family            text,
  provenance_class  provenance_class not null,
  provenance_source text not null,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);
create trigger skill_touch before update on skill
  for each row execute function touch_updated_at();

create table role_requirement (
  id              uuid primary key default gen_random_uuid(),
  target_role_id  uuid not null references target_role(id) on delete cascade,
  skill_id        uuid not null references skill(id) on delete restrict,
  weight          numeric(4,3) not null check (weight > 0 and weight <= 1),
  is_core         boolean not null default false,
  -- INV-4: market demand is market information and needs a dated source.
  demand_ratio            numeric(4,3) check (demand_ratio >= 0 and demand_ratio <= 1),
  demand_source           text,
  demand_observed_at      date,
  created_at      timestamptz not null default now(),
  unique (target_role_id, skill_id),
  constraint role_requirement_demand_sourced check (
    demand_ratio is null or (demand_source is not null and demand_observed_at is not null)
  )
);

comment on constraint role_requirement_demand_sourced on role_requirement is
  'INV-4: no market information without a tagged, dated source.';

create table career_goal (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid not null references app_user(id) on delete cascade,
  target_role_id  uuid not null references target_role(id) on delete restrict,
  confirmed_at    timestamptz not null,
  is_current      boolean not null default true,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create unique index career_goal_one_current
  on career_goal(user_id) where is_current;
create trigger career_goal_touch before update on career_goal
  for each row execute function touch_updated_at();

comment on index career_goal_one_current is
  'Exactly one current goal per user. Changing goals keeps history rather than overwriting it.';

-- ═══════════════════════ content: specs and rubrics ════════════════════════

create table activity_spec (
  id                uuid primary key default gen_random_uuid(),
  slug              text not null,
  version           text not null,
  status            content_status not null default 'draft',
  title_ar          text not null,
  ai_usage_mode     ai_usage_mode not null,
  estimated_minutes int check (estimated_minutes > 0),
  -- The spec body genuinely varies by activity type; documented JSONB use.
  spec              jsonb not null,
  -- D-030: no activity may yield Verified before SME approval.
  sme_approved_by   uuid,
  sme_approved_at   timestamptz,
  can_yield_verified boolean not null default false,
  published_at      timestamptz,
  created_at        timestamptz not null default now(),
  unique (slug, version),
  constraint activity_spec_published_is_frozen check (
    status <> 'published' or published_at is not null
  ),
  constraint activity_spec_verified_needs_sme check (
    can_yield_verified = false or (sme_approved_by is not null and sme_approved_at is not null)
  )
);

comment on constraint activity_spec_verified_needs_sme on activity_spec is
  'D-030: SME approval is a blocking gate before an activity can produce Verified evidence.';
comment on column activity_spec.spec is
  'JSONB justified: activity bodies differ per type and are versioned content, not queryable domain state.';

create table rubric_version (
  id                uuid primary key default gen_random_uuid(),
  activity_spec_id  uuid not null references activity_spec(id) on delete restrict,
  version           text not null,
  status            content_status not null default 'draft',
  criteria          jsonb not null,
  published_at      timestamptz,
  created_at        timestamptz not null default now(),
  unique (activity_spec_id, version),
  constraint rubric_published_is_frozen check (
    status <> 'published' or published_at is not null
  )
);

comment on column rubric_version.criteria is
  'JSONB justified: rubric criteria are versioned, frozen content. A published rubric is never edited.';

-- ══════════════════════════ projects and work ══════════════════════════════

create table project (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null references app_user(id) on delete cascade,
  title             text not null,
  kind              text not null check (kind in ('platform_activity', 'personal_project')),
  description       text,
  activity_spec_id  uuid references activity_spec(id) on delete restrict,
  activity_spec_version text,
  status            text not null default 'draft'
                    check (status in ('draft','active','completed','evidenced','archived','withdrawn')),
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  -- Soft deletion: withdrawn work stays recoverable and evidence must not
  -- dangle (docs/blueprint/21: side states hide, they never delete).
  deleted_at        timestamptz,
  -- INV-7: a platform activity always references a published spec version.
  constraint project_activity_has_spec check (
    kind <> 'platform_activity'
    or (activity_spec_id is not null and activity_spec_version is not null)
  )
);
create trigger project_touch before update on project
  for each row execute function touch_updated_at();
create index project_user_idx on project(user_id) where deleted_at is null;

comment on constraint project_activity_has_spec on project is
  'INV-7: every Activity references a published Spec version.';

create table work_item (
  id          uuid primary key default gen_random_uuid(),
  project_id  uuid not null references project(id) on delete cascade,
  user_id     uuid not null references app_user(id) on delete cascade,
  title       text not null,
  status      text not null default 'draft'
              check (status in ('draft','active','completed','evidenced','archived','withdrawn')),
  position    int not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create trigger work_item_touch before update on work_item
  for each row execute function touch_updated_at();

-- ═════════════════════════ submissions and files ═══════════════════════════

create table submission (
  id                uuid primary key default gen_random_uuid(),
  project_id        uuid not null references project(id) on delete cascade,
  user_id           uuid not null references app_user(id) on delete cascade,
  state             text not null default 'received'
                    check (state in ('received','locked','validated','checked','evaluated',
                                     'verified','closed','rejected_format','blocked_by_checks',
                                     'in_human_review','resubmitted')),
  repository_url    text,
  locked_at         timestamptz,
  -- A correction creates a NEW submission linked to the old one; the original
  -- is never edited (docs/blueprint/21 §3).
  supersedes_submission_id uuid references submission(id) on delete restrict,
  created_at        timestamptz not null default now(),
  constraint submission_locked_has_time check (state = 'received' or locked_at is not null)
);
create index submission_project_idx on submission(project_id);

comment on constraint submission_locked_has_time on submission is
  'After locking there is no editing; the lock time is part of the evidence chain.';

create table submission_file (
  id              uuid primary key default gen_random_uuid(),
  submission_id   uuid not null references submission(id) on delete cascade,
  user_id         uuid not null references app_user(id) on delete cascade,
  bucket          text not null,
  object_path     text not null,
  content_type    text not null,
  size_bytes      bigint not null check (size_bytes > 0),
  checksum_sha256 text not null,
  -- Raw uploads never leave the account by any path (see sharing rules).
  privacy_class   privacy_class not null default 'private_never_shareable',
  created_at      timestamptz not null default now(),
  unique (bucket, object_path),
  constraint submission_file_never_shareable check (privacy_class = 'private_never_shareable')
);

comment on constraint submission_file_never_shareable on submission_file is
  'A raw upload is never reachable through a recruiter report, public profile or share link.';

-- ═════════════════════════ AI usage disclosure ═════════════════════════════

create table ai_disclosure (
  id              uuid primary key default gen_random_uuid(),
  submission_id   uuid not null unique references submission(id) on delete cascade,
  user_id         uuid not null references app_user(id) on delete cascade,
  mode            ai_usage_mode not null,
  declared_use    text[] not null default '{}',
  explanation     text,
  declared_at     timestamptz not null default now(),
  -- Disclosure never lowers a score. There is deliberately no penalty column:
  -- a field that does not exist cannot be misused.
  constraint ai_disclosure_prohibited_means_none check (
    mode <> 'ai_prohibited' or cardinality(declared_use) = 0
  )
);

comment on table ai_disclosure is
  'No score-penalty column exists by design. Disclosure is never punitive (docs/standards/08).';

-- ═══════════════════════════ evaluation history ════════════════════════════

create table evaluation (
  id              uuid primary key default gen_random_uuid(),
  submission_id   uuid not null references submission(id) on delete restrict,
  user_id         uuid not null references app_user(id) on delete cascade,
  state           text not null default 'queued'
                  check (state in ('queued','running','completed','failed',
                                   'queued_for_human','disputed','revised')),
  queued_at       timestamptz not null default now(),
  completed_at    timestamptz
);

-- APPEND-ONLY. A re-evaluation inserts a new row pointing at the old one.
-- There is no status column to flip and no row to rewrite.
create table evaluation_result (
  id                    uuid primary key default gen_random_uuid(),
  evaluation_id         uuid not null references evaluation(id) on delete restrict,
  submission_id         uuid not null references submission(id) on delete restrict,
  user_id               uuid not null references app_user(id) on delete cascade,
  outcome               evaluation_outcome not null,
  -- INV-2: no evaluation without a published rubric version.
  rubric_version_id     uuid references rubric_version(id) on delete restrict,
  -- INV-7: the frozen spec the work was assigned under.
  activity_spec_id      uuid references activity_spec(id) on delete restrict,
  activity_spec_version text,
  supersedes_result_id  uuid references evaluation_result(id) on delete restrict,
  human_reviewer_id     uuid references app_user(id) on delete restrict,
  -- FR-P-037: which role the reviewer acted in, recorded separately from who.
  role_performed        role_performed,
  evaluated_at          timestamptz not null default now(),

  constraint evaluation_result_scored_needs_rubric check (
    outcome not in ('passed','below_threshold')
    or (rubric_version_id is not null
        and activity_spec_id is not null
        and activity_spec_version is not null)
  ),
  constraint evaluation_result_reviewer_has_role check (
    human_reviewer_id is null or role_performed is not null
  )
);
create index evaluation_result_eval_idx on evaluation_result(evaluation_id);
create unique index evaluation_result_supersede_once
  on evaluation_result(supersedes_result_id) where supersedes_result_id is not null;

comment on table evaluation_result is
  'Immutable history. Re-evaluation appends a superseding row; it never rewrites one.';
comment on constraint evaluation_result_scored_needs_rubric on evaluation_result is
  'INV-2 and INV-7 together: a scored result requires a published rubric and spec version.';

create table evaluation_criterion_score (
  id                    uuid primary key default gen_random_uuid(),
  evaluation_result_id  uuid not null references evaluation_result(id) on delete cascade,
  criterion_key         text not null,
  score                 numeric(6,3) not null,
  max_score             numeric(6,3) not null check (max_score > 0),
  -- A score with no written justification is not a result (doc 11 §5).
  rationale             text not null check (length(btrim(rationale)) > 0),
  supporting_excerpt    text,
  skill_id              uuid references skill(id) on delete restrict,
  confidence            numeric(4,3) check (confidence >= 0 and confidence <= 1),
  created_at            timestamptz not null default now(),
  unique (evaluation_result_id, criterion_key),
  constraint criterion_score_in_range check (score >= 0 and score <= max_score)
);

create table integrity_check (
  id                    uuid primary key default gen_random_uuid(),
  evaluation_result_id  uuid not null references evaluation_result(id) on delete cascade,
  check_key             text not null,
  -- user_facing checks may be explained to the user; assessment_only may not.
  classification        text not null check (classification in ('user_facing','assessment_only')),
  passed                boolean,
  signal                text,
  created_at            timestamptz not null default now(),
  unique (evaluation_result_id, check_key)
);

comment on column integrity_check.classification is
  'assessment_only detail is never exposed to the user or through any share path.';

create table human_review (
  id                    uuid primary key default gen_random_uuid(),
  evaluation_id         uuid not null references evaluation(id) on delete restrict,
  reviewer_id           uuid not null references app_user(id) on delete restrict,
  role_performed        role_performed not null,
  state                 text not null default 'queued'
                        check (state in ('queued','assigned','in_review','decided','applied',
                                         'info_requested','reassigned','expired_sla')),
  -- A decision requires a written justification (FR-P-037).
  decision              text,
  justification         text,
  contradicted_automated boolean,
  conflict_of_interest  boolean not null default false,
  decided_at            timestamptz,
  applied_at            timestamptz,
  created_at            timestamptz not null default now(),
  constraint human_review_decided_has_justification check (
    state not in ('decided','applied')
    or (decision is not null and length(btrim(coalesce(justification,''))) > 0)
  )
);

comment on constraint human_review_decided_has_justification on human_review is
  'FR-P-037: a decision with no written justification cannot be recorded.';

-- ═════════════════════════════ evidence ════════════════════════════════════

create table evidence (
  id                    uuid primary key default gen_random_uuid(),
  user_id               uuid not null references app_user(id) on delete cascade,
  skill_id              uuid not null references skill(id) on delete restrict,
  -- Where the evidence came from, and how strong that source is.
  source_strength       evidence_source_strength not null,
  evaluation_result_id  uuid references evaluation_result(id) on delete restrict,
  project_id            uuid references project(id) on delete restrict,
  -- INV-5: every fact carries provenance.
  provenance_class      provenance_class not null,
  provenance_source     text not null,
  confidence            numeric(4,3) check (confidence >= 0 and confidence <= 1),
  created_at            timestamptz not null default now(),
  -- Withdrawing evidence cascades to what was derived from it, so a soft
  -- marker rather than a delete.
  withdrawn_at          timestamptz,
  withdrawn_reason      text,

  -- Platform-strength evidence must come from an actual evaluation.
  constraint evidence_platform_needs_evaluation check (
    source_strength not in ('platform_controlled','platform_observed')
    or evaluation_result_id is not null
  ),
  constraint evidence_withdrawn_has_reason check (
    withdrawn_at is null or length(btrim(coalesce(withdrawn_reason,''))) > 0
  )
);
create index evidence_user_skill_idx on evidence(user_id, skill_id) where withdrawn_at is null;

-- The claim: the user's current state for one skill.
create table skill_claim (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null references app_user(id) on delete cascade,
  skill_id          uuid not null references skill(id) on delete restrict,
  state             evidence_state not null default 'self_reported',
  -- INV-1: at demonstrated and above, a claim points at real evidence.
  -- The FK makes the rule structural; the CHECK makes it conditional.
  primary_evidence_id uuid references evidence(id) on delete restrict,
  state_reason      text not null,
  recency_status    text not null default 'current'
                    check (recency_status in ('current','aging','historical')),
  side_state        text check (side_state in ('under_review','withdrawn','suspended','superseded')),
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  unique (user_id, skill_id),

  constraint claim_requires_evidence check (
    evidence_ordinal(state) < evidence_ordinal('demonstrated')
    or primary_evidence_id is not null
  ),
  -- Source strength caps the reachable level; enforced again per-row in the
  -- transition trigger below, where the evidence row is available.
  constraint claim_gap_is_not_stored check (state <> 'gap')
);
create trigger skill_claim_touch before update on skill_claim
  for each row execute function touch_updated_at();

comment on constraint claim_requires_evidence on skill_claim is
  'INV-1: no Claim without Evidence. Structural, not application logic.';
comment on constraint claim_gap_is_not_stored on skill_claim is
  'gap is the ABSENCE of a claim, so it is a display ordinal, never a stored row.';

-- APPEND-ONLY ladder history. Every transition, with its reason and actor.
create table evidence_transition (
  id                    uuid primary key default gen_random_uuid(),
  skill_claim_id        uuid not null references skill_claim(id) on delete cascade,
  user_id               uuid not null references app_user(id) on delete cascade,
  from_state            evidence_state not null,
  to_state              evidence_state not null,
  transition_rule_id    text not null,
  evaluation_result_id  uuid references evaluation_result(id) on delete restrict,
  human_reviewer_id     uuid references app_user(id) on delete restrict,
  actor_kind            actor_kind not null,
  -- INV-8: no silent transition, and none without a recorded reason.
  reason                text not null check (length(btrim(reason)) > 0),
  occurred_at           timestamptz not null default now(),

  -- Forward-only. v1 models no backward movement at all.
  constraint transition_is_forward check (
    evidence_ordinal(to_state) > evidence_ordinal(from_state)
  ),
  -- INV-3: an agent may propose, never execute.
  constraint transition_actor_is_not_agent check (actor_kind <> 'ai_agent'),
  -- Verified is never granted without a named human reviewer.
  constraint transition_verified_needs_human check (
    to_state <> 'verified' or human_reviewer_id is not null
  ),
  -- Promotion to demonstrated or above requires an evaluated submission.
  constraint transition_promotion_needs_evaluation check (
    evidence_ordinal(to_state) < evidence_ordinal('demonstrated')
    or evaluation_result_id is not null
  )
);
create index evidence_transition_claim_idx on evidence_transition(skill_claim_id, occurred_at);

comment on constraint transition_is_forward on evidence_transition is
  'Forward-only ladder (0 to 4). Backward movement is not modelled in v1.';
comment on constraint transition_actor_is_not_agent on evidence_transition is
  'INV-3: agents propose; they never write to the career graph.';

-- ══════════════════════ professional assets and scores ═════════════════════

create table professional_asset (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null references app_user(id) on delete cascade,
  kind              text not null
                    check (kind in ('cv_bullet','linkedin_skill','case_study','showcase_project')),
  title             text not null,
  body              text not null,
  status            text not null default 'generated'
                    check (status in ('generated','user_edited','approved','published','unpublished')),
  provenance_class  provenance_class not null,
  provenance_source text not null,
  -- A model may have helped phrase it; substance still comes from evidence.
  drafting_aid_used boolean not null default false,
  privacy_class     privacy_class not null default 'private_publishable',
  -- Nothing is applied or published before the user approves it.
  user_approved_at  timestamptz,
  published_at      timestamptz,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),

  constraint asset_published_needs_approval check (
    published_at is null or user_approved_at is not null
  )
);
create trigger professional_asset_touch before update on professional_asset
  for each row execute function touch_updated_at();

comment on constraint asset_published_needs_approval on professional_asset is
  'No system-generated professional wording is ever applied or published without explicit user approval.';

-- Which evidence produced an asset. Empty means the asset is not evidence-backed.
create table asset_evidence (
  asset_id    uuid not null references professional_asset(id) on delete cascade,
  evidence_id uuid not null references evidence(id) on delete restrict,
  primary key (asset_id, evidence_id)
);

create table cv_version (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null references app_user(id) on delete cascade,
  version_number    int not null,
  language          text not null check (language in ('ar','en')),
  -- The rendered document lives in storage, never in the row.
  document_bucket   text,
  document_path     text,
  content_snapshot  jsonb not null,
  created_at        timestamptz not null default now(),
  unique (user_id, version_number, language)
);

comment on column cv_version.content_snapshot is
  'JSONB justified: a point-in-time snapshot kept for before/after comparison, not queryable domain state.';

create table readiness_score (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null references app_user(id) on delete cascade,
  kind              text not null check (kind in ('profile','cv','linkedin')),
  value             int not null check (value >= 0 and value <= 100),
  weights_version   text not null,
  computed_at       timestamptz not null default now(),
  -- The event that moved it. Filling in fields is never one of them.
  triggered_by_event text not null,
  previous_score_id uuid references readiness_score(id) on delete set null,
  constraint score_trigger_is_work_derived check (
    triggered_by_event in ('project.completed','skill.demonstrated','evidence.created',
                           'achievement.generated','cv.updated','linkedin.updated','initial.computed')
  )
);
create index readiness_score_user_kind_idx on readiness_score(user_id, kind, computed_at desc);

comment on constraint score_trigger_is_work_derived on readiness_score is
  'Scores change from work, never from filling in profile fields (frozen design section 9).';

create table score_component (
  id                uuid primary key default gen_random_uuid(),
  readiness_score_id uuid not null references readiness_score(id) on delete cascade,
  component_key     text not null,
  status            text not null check (status in ('weak','fair','good','strong')),
  -- A status word with no reason sentence explains nothing to the user.
  reason            text not null check (length(btrim(reason)) > 0),
  normalised        numeric(5,4) not null check (normalised >= 0 and normalised <= 1),
  weight            numeric(5,4) not null check (weight >= 0 and weight <= 1),
  unique (readiness_score_id, component_key)
);

create table cv_assessment (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null references app_user(id) on delete cascade,
  cv_version_id     uuid references cv_version(id) on delete set null,
  readiness_score_id uuid not null references readiness_score(id) on delete restrict,
  ats_ready         boolean,
  created_at        timestamptz not null default now()
);

create table linkedin_assessment (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null references app_user(id) on delete cascade,
  readiness_score_id uuid not null references readiness_score(id) on delete restrict,
  sections          jsonb not null,
  created_at        timestamptz not null default now()
);

comment on column linkedin_assessment.sections is
  'JSONB justified: the eight LinkedIn section names are an external platform contract we do not own.';

create table case_study (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null references app_user(id) on delete cascade,
  asset_id          uuid not null unique references professional_asset(id) on delete cascade,
  -- Four fixed sections. Columns, not JSON, because they are a product rule.
  context           text not null,
  problem           text not null,
  what_i_built      text not null,
  result            text not null,
  -- Written only from an evaluated project, never from self-description.
  source_evaluation_result_id uuid not null references evaluation_result(id) on delete restrict,
  created_at        timestamptz not null default now()
);

comment on table case_study is
  'Four fixed sections are a product rule, so they are columns. Written only from an evaluated project.';

create table recruiter_report (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null references app_user(id) on delete cascade,
  generated_at      timestamptz not null default now(),
  eligible          boolean not null,
  ineligible_reason text,
  constraint recruiter_report_ineligible_has_reason check (
    eligible or length(btrim(coalesce(ineligible_reason,''))) > 0
  )
);

create table recruiter_report_item (
  id                uuid primary key default gen_random_uuid(),
  report_id         uuid not null references recruiter_report(id) on delete cascade,
  observation       text not null,
  why               text not null,
  moves_score       text check (moves_score in ('profile','cv','linkedin')),
  expected_delta    int,
  -- INV-5: every item traces to a concrete field or evidence row.
  traces_to_kind    text not null check (traces_to_kind in ('field','evidence')),
  traces_to_ref     text not null check (length(btrim(traces_to_ref)) > 0),
  position          int not null default 0
);

comment on constraint recruiter_report_item_traces_to_kind_check on recruiter_report_item is
  'INV-5: a recommendation points at real information in the account, not a general estimate.';

-- ═══════════════════════ publishing, sharing, privacy ══════════════════════

create table public_profile (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null unique references app_user(id) on delete cascade,
  slug              citext not null unique,
  visibility        visibility not null default 'private',
  published_at      timestamptz,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  constraint public_profile_published_is_visible check (
    published_at is null or visibility <> 'private'
  )
);
create trigger public_profile_touch before update on public_profile
  for each row execute function touch_updated_at();

create table share_link (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid not null references app_user(id) on delete cascade,
  resource_kind   text not null
                  check (resource_kind in ('case_study','public_profile','recruiter_report')),
  resource_id     uuid not null,
  token_hash      text not null unique,
  -- OPEN-016 is unresolved, so the conservative reading is enforced: every
  -- link expires, and none is indexable.
  expires_at      timestamptz not null,
  revoked_at      timestamptz,
  indexable       boolean not null default false,
  created_at      timestamptz not null default now(),
  constraint share_link_not_indexable check (indexable = false)
);
create index share_link_active_idx on share_link(resource_kind, resource_id)
  where revoked_at is null;

comment on constraint share_link_not_indexable on share_link is
  'OPEN-016 (indexing, expiry, revocation of public links) is open; the safe reading applies until it closes.';

create table consent (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references app_user(id) on delete cascade,
  purpose       text not null,
  granted       boolean not null,
  policy_version text not null,
  recorded_at   timestamptz not null default now()
);

comment on table consent is
  'Append-only: withdrawal is a NEW row, never an edit (docs/blueprint/21 section 11).';

-- ═════════════════════ learning, activities, notifications ═════════════════

create table learning_gap (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid not null references app_user(id) on delete cascade,
  skill_id        uuid not null references skill(id) on delete restrict,
  career_goal_id  uuid not null references career_goal(id) on delete cascade,
  priority        int not null,
  -- Derived from role requirements and current claims; never hand-entered.
  provenance_class provenance_class not null default 'system_derived',
  created_at      timestamptz not null default now(),
  resolved_at     timestamptz,
  unique (user_id, skill_id, career_goal_id)
);

create table learning_resource (
  id                uuid primary key default gen_random_uuid(),
  skill_id          uuid not null references skill(id) on delete restrict,
  title             text not null,
  url               text,
  language          text check (language in ('ar','en')),
  -- INV-5 and the pack rule: no invented URLs. Unverified stays unverified.
  provenance_class  provenance_class not null,
  provenance_source text not null,
  verification_status text not null default 'source_to_verify'
                    check (verification_status in ('source_to_verify','verified','rejected')),
  created_at        timestamptz not null default now(),
  constraint learning_resource_verified_has_url check (
    verification_status <> 'verified' or url is not null
  )
);

comment on constraint learning_resource_verified_has_url on learning_resource is
  'A resource is never marked verified without a real URL. SOURCE TO VERIFY is the honest default.';

create table practice_activity (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null references app_user(id) on delete cascade,
  skill_id          uuid not null references skill(id) on delete restrict,
  activity_spec_id  uuid references activity_spec(id) on delete restrict,
  completed_at      timestamptz,
  created_at        timestamptz not null default now()
);

comment on table practice_activity is
  'Practice and learning completion never change an evidence state (docs/design handoff section 8).';

create table notification (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references app_user(id) on delete cascade,
  type          text not null check (type in ('success','improvement','attention','info','critical')),
  body_ar       text not null,
  body_en       text,
  action_label  text,
  action_href   text,
  -- The design remembers dismissal per event, so it is stored per row.
  read_at       timestamptz,
  dismissed_at  timestamptz,
  source_event_id uuid,
  created_at    timestamptz not null default now()
);
create index notification_user_unread_idx on notification(user_id, created_at desc)
  where read_at is null and dismissed_at is null;

-- ═══════════════════════════════ audit trail ═══════════════════════════════

-- APPEND-ONLY. Product data, not telemetry: it is subject to retention policy,
-- export rights and legal hold, and it is never mixed with operational logs.
create table audit_event (
  id              uuid primary key default gen_random_uuid(),
  event_type      text not null,
  -- Null for platform-level events with no single subject.
  user_id         uuid references app_user(id) on delete restrict,
  actor_kind      actor_kind not null,
  actor_id        uuid,
  role_performed  role_performed,
  subject_table   text not null,
  subject_id      uuid,
  -- INV-8: no event without a recorded reason.
  reason          text not null check (length(btrim(reason)) > 0),
  payload         jsonb not null default '{}'::jsonb,
  occurred_at     timestamptz not null default now(),
  constraint audit_event_reviewer_has_role check (
    actor_kind <> 'human_reviewer' or role_performed is not null
  )
);
create index audit_event_subject_idx on audit_event(subject_table, subject_id, occurred_at desc);
create index audit_event_user_idx on audit_event(user_id, occurred_at desc);

comment on table audit_event is
  'Append-only product data. Retention, export and legal hold apply. Never mixed with operational telemetry.';
comment on column audit_event.payload is
  'JSONB justified: event shapes differ per type. Queryable fields are promoted to columns.';

-- Metering for every model call (INV-6). No call exists outside this table.
create table model_call (
  id              uuid primary key default gen_random_uuid(),
  gateway_call_id text not null unique,
  user_id         uuid references app_user(id) on delete set null,
  provider        text not null,
  model           text not null,
  purpose         text not null,
  input_tokens    int not null check (input_tokens >= 0),
  output_tokens   int not null check (output_tokens >= 0),
  cost_units      numeric(12,6),
  occurred_at     timestamptz not null default now()
);

comment on table model_call is
  'INV-6: every model call goes through the gateway and is metered. A call with no row here did not happen.';

-- Market facts kept separately so INV-4 is enforced in one place.
create table market_fact (
  id                uuid primary key default gen_random_uuid(),
  statement         text not null,
  skill_id          uuid references skill(id) on delete cascade,
  target_role_id    uuid references target_role(id) on delete cascade,
  provenance_class  provenance_class not null
                    check (provenance_class in ('authoritative','curated')),
  provenance_source text not null check (length(btrim(provenance_source)) > 0),
  observed_at       date not null,
  sample_size       int check (sample_size > 0),
  created_at        timestamptz not null default now()
);

comment on constraint market_fact_provenance_class_check on market_fact is
  'INV-4: a market claim may not rest on model output. Only authoritative or curated sources.';

-- ══════════════════════════ background job queue ═══════════════════════════

-- Postgres-backed by decision. Enqueueing happens inside the same transaction
-- as the write that caused it, so a submission can never exist without its
-- evaluation job. The table is deliberately generic so the driver stays
-- replaceable.
create table job (
  id            uuid primary key default gen_random_uuid(),
  queue         text not null,
  payload       jsonb not null,
  state         text not null default 'pending'
                check (state in ('pending','running','succeeded','failed','dead')),
  attempts      int not null default 0,
  max_attempts  int not null default 3,
  run_after     timestamptz not null default now(),
  last_error    text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create index job_pickup_idx on job(queue, run_after) where state = 'pending';
create trigger job_touch before update on job
  for each row execute function touch_updated_at();

comment on table job is
  'Transactional enqueue: a job is committed with the write that caused it, so work is never lost.';
